name: file.io-cli
version: 1.0.3
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
url: https://github.com/NiklasRosenstein/file.io-cli
modulename: file_io_cli
description: Command-line tool to upload files to https://file.io
requirements:
- python ^3.3
- clipboard ^0.0.4
- requests ^2.25.1
source-directory: .
entrypoints:
  console_scripts:
  - file.io-cli = file_io_cli:_entry_point
